function resume_generation(path)
arguments
    path;
end
% it reasumes the generation with the parameters obtained from the given
% path
    addpath('./utils')
    addpath('./generators')
    addpath('./fwc')
        
    path = fullfile("data", path);
    [dist_settings, hyparams] = parse_settings(path);

    [~, ~] = vc_correction('none', ...
            hyparams.nb_subj, hyparams.nb_infeat, ...
            hyparams.nb_outfeat, hyparams.nb_timesteps, ...
            dist_settings.rsquared_target, ...
            'sec_cluster_voxels', hyparams.second_cluster, ...
            'numb_permutations', hyparams.numb_permutations, ...
            'saving', 1, ...
            'save_res', 0, ...
            'greater_dist', 1, ...
            'prev_settings', struct('hyparams', hyparams, ...
            'dist_settings', dist_settings));
end

function [dist_settings, hyparams] =  ...
        parse_settings(path)
    dist_settings = load(fullfile(path, "dist_settings"));
    dist_settings = dist_settings.dist_settings;
    hyparams = load(fullfile(path, "hyparams"));
    hyparams = hyparams.hyparams;
end